### Get all users
GET http://localhost:3030/mongo/users

### Create a new user
POST http://localhost:3030/mongo/users
Content-Type: application/json

{
    "username":"earn238",
    "name" : "Test Person",
    "email" :"testperson012@example.com"
}

### Update a new user
PUT http://localhost:3030/mongo/users/680a0ff728d491dc2b74bfee
Content-Type: application/json

{
    "username":"earn145",
    "name" : "Test Person1",
    "email" :"testperson002@example.com"
}

###Register a new user

POST http://localhost:3030/mongo/auth/register
Content-Type: application/json

{
    "fullName": "Va",
    "username":"va2",
    "email": "va2@example.com",
    "password": "va1232"
}

###Login with the registered user

POST http://localhost:3030/mongo/auth/login
Content-Type: application/json

{
    "email": "va2@example.com",
    "password": "va1232"
}

###delete user
DELETE http://localhost:3030/mongo/users/680b18c4a6a99157f97f7758
Content-Type: application/json


### Get all notes
GET http://localhost:3030/mongo/notes

### Create a new note
POST http://localhost:3030/mongo/notes
Content-Type: application/json

{
    "title" : "Test Note",
    "content" :"testnote@example.com",
    "tags": ["nodejs","express"],
    "isPinned": false,
    "userId": "6809c2ea12a27dedd019aac6"
}

### Add new note (protected Route)
POST http://localhost:3030/mongo/add-note
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBiMThjNGE2YTk5MTU3Zjk3Zjc3NTgiLCJpYXQiOjE3NDU4MjM3NDksImV4cCI6MTc0NTgyNzM0OX0.JiakUSijbu3bph_6crXRKt5khxG682FzNkmXrLVD6tY

{
    "title": "funny1",
    "content": "This is funny1",
    "tags": ["important","yesterday"],
    "isPinned": true
}

### Get all notes for the login user
GET http://localhost:3030/mongo/get-notes-by-id
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBiMThjNGE2YTk5MTU3Zjk3Zjc3NTgiLCJpYXQiOjE3NDU4MjM3NDksImV4cCI6MTc0NTgyNzM0OX0.JiakUSijbu3bph_6crXRKt5khxG682FzNkmXrLVD6tY


### Search notes 
GET http://localhost:3030/mongo/search-notes?query=this
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBiMThjNGE2YTk5MTU3Zjk3Zjc3NTgiLCJpYXQiOjE3NDU4MjM3NDksImV4cCI6MTc0NTgyNzM0OX0.JiakUSijbu3bph_6crXRKt5khxG682FzNkmXrLVD6tY